- hosts: test_ansible
  become: True
  gather_facts: no
  connection: ssh

  tasks:
  - name: "Print Date"
    shell: date
    register: date_output

  - debug: var=date_output

  - name: "Install htop package"
    yum: pkg=htop state=installed
